# FROM alpine:3.14
# LABEL maintainer="Sanskar Sharma <sanskar2996@gmail.com>"

# ADD crontab.txt /crontab.txt
# ADD backup.sh /backup.sh
# COPY entry.sh /entry.sh



# CMD ["/entry.sh"]

FROM alpine:3.3

ADD crontab.txt /crontab.txt
ADD script.sh /script.sh
COPY entry.sh /entry.sh
RUN apk update \
    && apk add postgresql-client curl \
    && chmod 755 /script.sh /entry.sh \
    && /usr/bin/crontab /crontab.txt

CMD ["/entry.sh"]
