version: '3'
services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_pg_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backup_network
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - backup_network

  backup_cron:
    build: ./DB_backup
    container_name: basic_cron
    tty: true
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_pg_db
    networks:
      - backup_network

networks:
  backup_network:


#docker-compose -f docker-compose.override.yml up --build
#docker-compose up --build
